const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
const ADD_PRODUCTS_TO_BASKET = 'ADD_PRODUCTS_TO_BASKET';
const UPDATE_PRODUCT_FROM_BASKET = 'UPDATE_PRODUCT_FROM_BASKET';
const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET';
const CLEAR_PRODUCTS_FROM_BASKET = 'CLEAR_PRODUCTS_FROM_BASKET';

export {
    ADD_PRODUCT_TO_BASKET,
    ADD_PRODUCTS_TO_BASKET,
    UPDATE_PRODUCT_FROM_BASKET,
    REMOVE_PRODUCT_FROM_BASKET,
    CLEAR_PRODUCTS_FROM_BASKET,
};

